#!/bin/sh

sudo pacman -Syu     \
  age                \
  alacritty          \
  binutils           \
  cloc               \
  curl               \
  ffmpeg             \
  fzf                \
  git                \
  gnome-disk-utility \
  htop               \
  keepassxc          \
  less               \
  lm_sensors         \
  lsof               \
  man-db             \
  man-pages          \
  moreutils          \
  mpv                \
  neovim             \
  pciutils           \
  ripgrep            \
  rofi               \
  tmux               \
  waybar             \
  wget               \
  wl-clipboard       \
  zsh

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay

yay -S           \
  brave-bin      \
  localsend      \
  neofetch       \
  obs-studio     \
  pinta          \
  popsicle       \
  qbittorrent    \
  signal-desktop \
  spotdl         \
  vesktop        \
  vscodium       \
  wireshark      \
  yt-dlp         \

./deploy.py
chsh -s /bin/zsh
shutdown now -r
