#!/bin/sh

sudo pacman -Syu     \
  age                \
  alacritty          \
  cloc               \
  curl               \
  ffmpeg             \
  fzf                \
  git                \
  gnome-disk-utility \
  htop               \
  keepassxc          \
  less               \
  lm_sensors         \
  lsof               \
  moreutils          \
  mpv                \
  neovim             \
  ripgrep            \
  rofi               \
  tmux               \
  waybar             \
  wget               \
  wl-clipboard       \
  zsh

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ..
rm -rf yay

yay -S      \
  brave-bin \
  localsend \
  neofetch  \
  popsicle  \
  vscodium  \

./deploy.py
chsh -s /bin/zsh
shutdown now -r
