#!/bin/sh

sudo pacman -Syu     \
  age                \
  binutils           \
  cloc               \
  dolphin            \
  gdb                \
  gnome-disk-utility \
  keepassxc          \
  kleopatra          \
  lsof               \
  moreutils          \
  pciutils           \
  signal-desktop     \
  tmux               \
  wget               \
  wireshark-qt       \
  wlsunset           \
  zsh

yay -Syu      \
  brave-bin   \
  gf2-git     \
  neofetch    \
  popsicle    \
  qbittorrent \
  spotdl      \
  vesktop     \
  vscodium    \
  yt-dlp

curl -fsSL https://opencode.ai/install | bash

./deploy.py
chsh -s /bin/zsh
shutdown now -r
