#!/bin/sh

sudo pacman -Syu     \
  age                \
  cloc               \
  gnome-disk-utility \
  keepassxc          \
  lsof               \
  moreutils          \
  pciutils           \
  tmux               \
  wget               \
  wireshark-qt       \
  zsh

yay -Syu         \
  neofetch       \
  popsicle       \
  qbittorrent    \
  spotdl         \
  vesktop        \
  vscodium       \
  yt-dlp

curl -fsSL https://opencode.ai/install | bash

./deploy.py
chsh -s /bin/zsh
shutdown now -r
