vim.cmd "syntax on"
vim.cmd "colorscheme unokai"
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.opt.autoindent = true
vim.opt.clipboard = "unnamedplus"
vim.opt.expandtab = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
