vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.autoindent = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.clipboard = "unnamedplus"
vim.opt.backspace = {"indent","eol","start"}
vim.cmd "syntax on"
vim.cmd "colorscheme unokai"
